# Generated by Django 6.0 on 2025-12-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('POF', 'Principles of Flying'), ('MET', 'Meteorology'), ('FPP', 'Flight Planning & Performance'), ('AGK', 'Aircraft General Knowledge'), ('NAV', 'Navigation'), ('HPL', 'Human Performance'), ('LAW', 'Air Law'), ('RTC', 'Radio & Communication')], max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('class_room', models.CharField(choices=[('PPL', 'PPL'), ('CPL', 'CPL'), ('ATPL', 'ATPL')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
