# Generated by Django 6.0 on 2026-01-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userrole_user_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approved',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('management', 'Management'), ('user', 'User'), ('staff', 'Staff'), ('instructor', 'Instructor'), ('student', 'Student')], default='user', max_length=20),
        ),
    ]
