# Generated by Django 6.0 on 2026-01-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_profession_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('management', 'Management'), ('staff', 'Staff'), ('instructor', 'Instructor'), ('student pilot', 'Student Pilot')], default='student', max_length=20),
        ),
    ]
