# Generated by Django 6.0 on 2026-01-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(choices=[('5Y-CCZ', '5Y-CCZ'), ('5Y-BZO', '5Y-BZO'), ('FMX', 'FMX')], max_length=10)),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('ex', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
