# Generated by Django 6.0 on 2025-12-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(choices=[('5Y-CCZ', '5Y-CCZ'), ('5Y-PZO', '5Y-PZO'), ('FMX', 'FMX')], max_length=10)),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('ex', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.RemoveField(
            model_name='scheduledflight',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='scheduled_flight',
        ),
        migrations.RemoveField(
            model_name='scheduledflight',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='scheduledflight',
            name='student',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='FlightLog',
        ),
        migrations.DeleteModel(
            name='ScheduledFlight',
        ),
    ]
