# Generated by Django 6.0 on 2026-01-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.CharField(choices=[('5Y-CCZ', '5Y-CCZ'), ('5Y-BZO', '5Y-BZO'), ('FMX', 'FMX')], max_length=10),
        ),
    ]
