# Generated by Django 6.0 on 2025-12-17 16:32

from django.db import migrations, models
from datetime import time

class Migration(migrations.Migration):

    dependencies = [
        ('notam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notam',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notam',
            name='date',
            field=models.DateField(default='2025-12-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam',
            name='location',
            field=models.CharField(default='today', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam',
            name='time',
            field=models.TimeField(default=time(0, 0)),
            preserve_default=False,
        ),
    ]
