# Generated by Django 6.0 on 2025-12-21 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notam', '0002_rename_message_notam_description_notam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
