# Generated by Django 6.0 on 2025-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notam', '0003_alter_notam_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notam',
            name='location',
        ),
        migrations.AddField(
            model_name='notam',
            name='airport',
            field=models.CharField(default='time', help_text='ICAO code e.g. HKJK, HKNW, HKMO', max_length=4),
            preserve_default=False,
        ),
    ]
